# SALARY PREDICTION OF SOFTWARE DEVELOPERS

# DESCRIPTION- 

This Project is made by A.KIRAN RAJ as a Machine Learning Research on Stackoverflow Developer Survey 2020 . Data is collected from Site:'https://insights.stackoverflow.com/survey'. CSV File Dataset : "survey_results_public.csv" consisting of more than 60000 Rows of data and 60 Columns. And made a Webapp for the same for Prediction of Salaries of Developer and Plot-Visualization of data of different Countries.

# Challenges faced:
1.Cleaned the data 
2.Dealed with Missing Values
3.Best columns were taken & Renamed to avoid confusion
4.Dealed with string values present in integer column
5.Made Transformation for the selected column values
6.Applied LabelEncoding on string column values
7.Made Machine Learning Model
8.checked its error
9.Predicted the model
10.Evaluated the model
11.Made Pickle file (dumped and Loaded the model)
12.Made a Webapp for Prediction and sidebar for Plot-Visualization

In [1]:
#IMPORTING THE LIBRARIES
#LOADED THE MODEL
import pandas as pd
df=pd.read_csv("/home/expert/MY_END_TO_END_PROJECTS/SoftwareDeveloperSurvey-Salary-Predictor-app/survey_results_public.csv")

In [2]:
#CHECKED ITS ROWS AND COLUMNS
df.shape

(64461, 61)

In [3]:
#FIRST 5 ROWS
df.head(5)

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [4]:
#LAST 5 ROWS
df.tail()

Respondent MainBranch Hobbyist  Age Age1stCode CompFreq  CompTotal  \
64456       64858        NaN      Yes  NaN         16      NaN        NaN   
64457       64867        NaN      Yes  NaN        NaN      NaN        NaN   
64458       64898        NaN      Yes  NaN        NaN      NaN        NaN   
64459       64925        NaN      Yes  NaN        NaN      NaN        NaN   
64460       65112        NaN      Yes  NaN        NaN      NaN        NaN   

       ConvertedComp        Country CurrencyDesc  ... SurveyEase SurveyLength  \
64456            NaN  United States          NaN  ...        NaN          NaN   
64457            NaN        Morocco          NaN  ...        NaN          NaN   
64458            NaN       Viet Nam          NaN  ...        NaN          NaN   
64459            NaN         Poland          NaN  ...        NaN          NaN   
64460            NaN          Spain          NaN  ...        NaN          NaN   

      Trans                                     UndergradMajor  \
64456   NaN  Computer science, computer engineering, or sof...   
64457   NaN                                                NaN   
64458   NaN                                                NaN   
64459   NaN                                                NaN   
64460   NaN  Computer science, computer engineering, or sof...   

            WebframeDesireNextYear                      WebframeWorkedWith  \
64456                          NaN                                     NaN   
64457                          NaN                                     NaN   
64458                          NaN                                     NaN   
64459  Angular;Angular.js;React.js                                     NaN   
64460          ASP.NET Core;jQuery  Angular;Angular.js;ASP.NET Core;jQuery   

      WelcomeChange WorkWeekHrs YearsCode      YearsCodePro  
64456           NaN         NaN        10  Less than 1 year  
64457           NaN         NaN       NaN               NaN  
64458           NaN         NaN       NaN               NaN  
64459           NaN         NaN       NaN               NaN  
64460           NaN         NaN       NaN               NaN  

[5 rows x 61 columns]

In [5]:
#CHECKED INFO ON WHOLE DATAFRAME
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Respondent                    64461 non-null  int64  
 1   MainBranch                    64162 non-null  object 
 2   Hobbyist                      64416 non-null  object 
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object 
 5   CompFreq                      40069 non-null  object 
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object 
 9   CurrencyDesc                  45472 non-null  object 
 10  CurrencySymbol                45472 non-null  object 
 11  DatabaseDesireNextYear        44070 non-null  object 
 12  DatabaseWorkedWith            49537 non-null  object 
 13  D

In [6]:
#ALL COLUMN NAMES IN DATAFRAMES
df.columns.tolist()

['Respondent',
 'MainBranch',
 'Hobbyist',
 'Age',
 'Age1stCode',
 'CompFreq',
 'CompTotal',
 'ConvertedComp',
 'Country',
 'CurrencyDesc',
 'CurrencySymbol',
 'DatabaseDesireNextYear',
 'DatabaseWorkedWith',
 'DevType',
 'EdLevel',
 'Employment',
 'Ethnicity',
 'Gender',
 'JobFactors',
 'JobSat',
 'JobSeek',
 'LanguageDesireNextYear',
 'LanguageWorkedWith',
 'MiscTechDesireNextYear',
 'MiscTechWorkedWith',
 'NEWCollabToolsDesireNextYear',
 'NEWCollabToolsWorkedWith',
 'NEWDevOps',
 'NEWDevOpsImpt',
 'NEWEdImpt',
 'NEWJobHunt',
 'NEWJobHuntResearch',
 'NEWLearn',
 'NEWOffTopic',
 'NEWOnboardGood',
 'NEWOtherComms',
 'NEWOvertime',
 'NEWPurchaseResearch',
 'NEWPurpleLink',
 'NEWSOSites',
 'NEWStuck',
 'OpSys',
 'OrgSize',
 'PlatformDesireNextYear',
 'PlatformWorkedWith',
 'PurchaseWhat',
 'Sexuality',
 'SOAccount',
 'SOComm',
 'SOPartFreq',
 'SOVisitFreq',
 'SurveyEase',
 'SurveyLength',
 'Trans',
 'UndergradMajor',
 'WebframeDesireNextYear',
 'WebframeWorkedWith',
 'WelcomeChange',
 'W

In [7]:
#STATISTICAL COUNT OF COLUMNS IN DATAFRAME
df.describe()

Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64461.000000  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.190464e+242   1.037561e+05     40.782174
std    18967.442360      9.585392            inf   2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00   0.000000e+00      1.000000
25%    16116.000000     24.000000   2.000000e+04   2.464800e+04     40.000000
50%    32231.000000     29.000000   6.300000e+04   5.404900e+04     40.000000
75%    49142.000000     35.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000    279.000000  1.111111e+247   2.000000e+06    475.000000

In [8]:
#CROSSCHECKED WITH STATS COUNT its like index column
df["Respondent"].value_counts()

2049     1
38264    1
3435     1
13676    1
15725    1
        ..
27288    1
25241    1
31386    1
29339    1
2047     1
Name: Respondent, Length: 64461, dtype: int64

In [9]:
#CROSSCHECKED WITH STATS COUNT - COUNT
df["Respondent"].value_counts().sum()

64461

In [10]:
#CROSSCHECKED WITH STATS COUNT - max
df["Respondent"].max()

65639

In [11]:
#CROSSCHECKED WITH STATS COUNT - min
df["Respondent"].min()

1

In [12]:
#CROSSCHECKED WITH STATS COUNT - mean
df["Respondent"].mean()

32554.07973813624

In [13]:
#CROSSCHECKED WITH STATS COUNT - std
df["Respondent"].std()

18967.4423599298

In [14]:
#CHECKED FOR NULL VALUES -BOOLEAN
df.isnull().any(axis=0)

Respondent            False
MainBranch             True
Hobbyist               True
Age                    True
Age1stCode             True
                      ...  
WebframeWorkedWith     True
WelcomeChange          True
WorkWeekHrs            True
YearsCode              True
YearsCodePro           True
Length: 61, dtype: bool

In [15]:
#NULL VALUES IN EACH COLUMN
df.isnull().sum()

Respondent                0
MainBranch              299
Hobbyist                 45
Age                   19015
Age1stCode             6561
                      ...  
WebframeWorkedWith    22182
WelcomeChange         11778
WorkWeekHrs           23310
YearsCode              6777
YearsCodePro          18112
Length: 61, dtype: int64

In [16]:
#SCHEMAS AND THERE PURPOSE

#EdLevel-Educational Level
#Employment - fulltime employee 
#YearsCodePro - Years of coding experience
#ConvertedComp - salary coverted to USD yearly salary 
#Country - which Country they belong to

#These 5 columns are taken and considered the best User details:
df[['EdLevel','Employment','YearsCodePro','ConvertedComp','Country']]

EdLevel  \
0      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1         Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2                                                  NaN   
3      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4         Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
...                                                ...   
64456  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
64457                                              NaN   
64458                        Primary/elementary school   
64459                                              NaN   
64460       Other doctoral degree (Ph.D., Ed.D., etc.)   

                                              Employment      YearsCodePro  \
0      Independent contractor, freelancer, or self-em...                27   
1                                     Employed full-time                 4   
2                                                    NaN               NaN   
3                                                    NaN                 4   
4                                     Employed full-time                 8   
...                                                  ...               ...   
64456                                 Employed full-time  Less than 1 year   
64457                                 Employed full-time               NaN   
64458                                                NaN               NaN   
64459                                 Employed full-time               NaN   
64460                                 Employed full-time               NaN   

       ConvertedComp             Country  
0                NaN             Germany  
1                NaN      United Kingdom  
2                NaN  Russian Federation  
3                NaN             Albania  
4                NaN       United States  
...              ...                 ...  
64456            NaN       United States  
64457            NaN             Morocco  
64458            NaN            Viet Nam  
64459            NaN              Poland  
64460            NaN               Spain  

[64461 rows x 5 columns]

In [17]:
#UNIQUE VALUES IN EMPLOYMENT COLUMN
print(df['Employment'].unique())

['Independent contractor, freelancer, or self-employed'
 'Employed full-time' nan 'Student' 'Not employed, but looking for work'
 'Employed part-time' 'Retired' 'Not employed, and not looking for work']


In [18]:
#UNIQUE VALUES IN EDUCATION COLUMN
print(df['EdLevel'].unique())

['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)'
 'Bachelor’s degree (B.A., B.S., B.Eng., etc.)' nan
 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)'
 'Professional degree (JD, MD, etc.)'
 'Some college/university study without earning a degree'
 'Associate degree (A.A., A.S., etc.)'
 'Other doctoral degree (Ph.D., Ed.D., etc.)' 'Primary/elementary school'
 'I never completed any formal education']


In [19]:
#UNIQUE VALUES IN COUNTRY COLUMN
print(df['Country'].unique())

['Germany' 'United Kingdom' 'Russian Federation' 'Albania' 'United States'
 'India' 'Tunisia' 'Spain' 'Netherlands' 'France' 'Belgium' 'Portugal'
 'Canada' 'China' 'Ukraine' 'Italy' 'Brazil' 'Austria' 'Mexico' 'Sweden'
 'Poland' 'Indonesia' 'Greece' 'Israel' 'Czech Republic'
 'Bosnia and Herzegovina' 'Bulgaria' 'Serbia' 'Switzerland' 'Hungary'
 'Nepal' 'Slovenia' 'Uruguay' 'Denmark' 'Pakistan' 'Taiwan' 'Romania'
 'Finland' 'Costa Rica' 'Nigeria' 'Chile' 'Turkey' 'Panama' 'Ireland'
 'Estonia' 'Philippines' 'Australia' 'Nomadic' 'Peru' 'Cyprus' 'Sri Lanka'
 'Kenya' 'Norway' 'Kyrgyzstan' 'Iran' 'Croatia' 'Egypt' 'Argentina'
 'Ghana' 'Latvia' 'Morocco' 'Bangladesh' 'Ecuador' 'Haiti'
 'Venezuela, Bolivarian Republic of...' 'Colombia' 'Lithuania'
 'El Salvador' 'Honduras' 'Ethiopia' 'Lebanon' 'Uganda' 'Algeria'
 'Viet Nam' 'Guatemala' 'Syrian Arab Republic' 'Afghanistan' 'Slovakia'
 'United Arab Emirates' 'Belarus' 'Sudan' 'South Africa' 'Jordan'
 'Georgia' 'United Republic of Tanzania' 'Ant

In [20]:
#SUM OF NULL-VALUES IN "ConvertedComp"
print(df['ConvertedComp'].isnull().sum())

29705


In [21]:
#Start
#These 5 columns are taken and considered the best User details:
df=df[['EdLevel','Employment','YearsCodePro','ConvertedComp','Country']]
#Renamed the ConvertedComp to Salary
df=df.rename({'ConvertedComp':'Salary'},axis=1)
df.head()

EdLevel  \
0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2                                              NaN   
3  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                          Employment YearsCodePro  Salary  \
0  Independent contractor, freelancer, or self-em...           27     NaN   
1                                 Employed full-time            4     NaN   
2                                                NaN          NaN     NaN   
3                                                NaN            4     NaN   
4                                 Employed full-time            8     NaN   

              Country  
0             Germany  
1      United Kingdom  
2  Russian Federation  
3             Albania  
4       United States

In [22]:
#Salary columns which are notnull
df[df['Salary'].notnull()]

EdLevel          Employment  \
7           Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
9        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  Employed full-time   
10          Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
11     Some college/university study without earning ...  Employed full-time   
12     Secondary school (e.g. American high school, G...  Employed full-time   
...                                                  ...                 ...   
64142  Secondary school (e.g. American high school, G...  Employed part-time   
64148       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
64152  Some college/university study without earning ...  Employed full-time   
64153       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
64154       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   

           YearsCodePro    Salary         Country  
7                    13  116000.0   United States  
9                     4   32315.0  United Kingdom  
10                    2   40070.0  United Kingdom  
11                    7   14268.0           Spain  
12                   20   38916.0     Netherlands  
...                 ...       ...             ...  
64142                 2     984.0         Nigeria  
64148                 5   19428.0        Colombia  
64152                20     200.0   United States  
64153                 3   15048.0           Chile  
64154  Less than 1 year   38759.0           Japan  

[34756 rows x 5 columns]

In [23]:
#Checking the Total Number of Entries
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   EdLevel       57431 non-null  object 
 1   Employment    63854 non-null  object 
 2   YearsCodePro  46349 non-null  object 
 3   Salary        34756 non-null  float64
 4   Country       64072 non-null  object 
dtypes: float64(1), object(4)
memory usage: 2.5+ MB


In [24]:
#Total Missing values in each columns
df.isnull().sum()

EdLevel          7030
Employment        607
YearsCodePro    18112
Salary          29705
Country           389
dtype: int64

In [25]:
#droped NaN rows
df=df.dropna()
df.head(10)

EdLevel  \
7        Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
11  Some college/university study without earning ...   
12  Secondary school (e.g. American high school, G...   
13                Associate degree (A.A., A.S., etc.)   
15       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
16       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
17       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
18       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                           Employment YearsCodePro     Salary  \
7                                  Employed full-time           13   116000.0   
9                                  Employed full-time            4    32315.0   
10                                 Employed full-time            2    40070.0   
11                                 Employed full-time            7    14268.0   
12                                 Employed full-time           20    38916.0   
13                                 Employed full-time            1    66000.0   
15  Independent contractor, freelancer, or self-em...           23   108576.0   
16                                 Employed full-time            3    79000.0   
17                                 Employed full-time           12  1260000.0   
18                                 Employed full-time            3    83400.0   

           Country  
7    United States  
9   United Kingdom  
10  United Kingdom  
11           Spain  
12     Netherlands  
13   United States  
15  United Kingdom  
16   United States  
17   United States  
18   United States

In [26]:
#Dealed with Missing Values
df.isnull().sum()

EdLevel         0
Employment      0
YearsCodePro    0
Salary          0
Country         0
dtype: int64

In [27]:
#Cross Cheacked the Non-Null Count
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34025 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   EdLevel       34025 non-null  object 
 1   Employment    34025 non-null  object 
 2   YearsCodePro  34025 non-null  object 
 3   Salary        34025 non-null  float64
 4   Country       34025 non-null  object 
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [28]:
#Checked the rows and columns after cleaning the data
df.shape

(34025, 5)

In [29]:
#Taking Actions on Each Columns
#Employment Column

df['Employment'].unique()

array(['Employed full-time',
       'Independent contractor, freelancer, or self-employed',
       'Employed part-time'], dtype=object)

In [30]:
#More number people is Employed full-time so it considered 
df['Employment'].value_counts()

Employed full-time                                      30019
Independent contractor, freelancer, or self-employed     2998
Employed part-time                                       1008
Name: Employment, dtype: int64

In [31]:
#Taking Employment column who are Employed fill-time only
df=df[df["Employment"]=='Employed full-time']
df

EdLevel          Employment  \
7           Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
9        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  Employed full-time   
10          Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
11     Some college/university study without earning ...  Employed full-time   
12     Secondary school (e.g. American high school, G...  Employed full-time   
...                                                  ...                 ...   
64135       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
64148       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
64152  Some college/university study without earning ...  Employed full-time   
64153       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   
64154       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  Employed full-time   

           YearsCodePro    Salary         Country  
7                    13  116000.0   United States  
9                     4   32315.0  United Kingdom  
10                    2   40070.0  United Kingdom  
11                    7   14268.0           Spain  
12                   20   38916.0     Netherlands  
...                 ...       ...             ...  
64135                 4   38208.0         Denmark  
64148                 5   19428.0        Colombia  
64152                20     200.0   United States  
64153                 3   15048.0           Chile  
64154  Less than 1 year   38759.0           Japan  

[30019 rows x 5 columns]

In [32]:
#DataFrame column with  Employed full-time is taken and the column is dropped 
df=df.drop("Employment",axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30019 entries, 7 to 64154
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   EdLevel       30019 non-null  object 
 1   YearsCodePro  30019 non-null  object 
 2   Salary        30019 non-null  float64
 3   Country       30019 non-null  object 
dtypes: float64(1), object(3)
memory usage: 1.1+ MB


In [33]:
#checked the Columns 
df.head(3)

EdLevel YearsCodePro    Salary  \
7      Bachelor’s degree (B.A., B.S., B.Eng., etc.)           13  116000.0   
9   Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            4   32315.0   
10     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            2   40070.0   

           Country  
7    United States  
9   United Kingdom  
10  United Kingdom

In [34]:
#Taking action on Country Column
#categories
df['Country'].value_counts()

United States                       7569
India                               2425
United Kingdom                      2287
Germany                             1903
Canada                              1178
                                    ... 
San Marino                             1
Guinea                                 1
Benin                                  1
Turkmenistan                           1
Saint Vincent and the Grenadines       1
Name: Country, Length: 154, dtype: int64

In [35]:
#Country Column contains multiple ones cutoff is taken 400 ,categories='df['Country'].value_counts()'
def short_categories(categories,cutoff):
    categorical_map={}
    for i in range(len(categories)):
        if categories.values[i]>=cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [36]:
#categories=df.Country.value_counts(),cutoff=400
country_map = short_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

Other                 8549
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: Country, dtype: int64

In [37]:
#Taking action on Salary column
#Considering Minimum salary for a Developer 10000 and less than 25000
df = df[df["Salary"] <= 250000]
df = df[df["Salary"] >= 10000]
df = df[df['Country'] != 'Other']

In [38]:
df.head(10)

EdLevel YearsCodePro    Salary  \
7        Bachelor’s degree (B.A., B.S., B.Eng., etc.)           13  116000.0   
9     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            4   32315.0   
10       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            2   40070.0   
11  Some college/university study without earning ...            7   14268.0   
12  Secondary school (e.g. American high school, G...           20   38916.0   
13                Associate degree (A.A., A.S., etc.)            1   66000.0   
16       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            3   79000.0   
18       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            3   83400.0   
23                 Professional degree (JD, MD, etc.)           20   91883.0   
25       Bachelor’s degree (B.A., B.S., B.Eng., etc.)           10   71093.0   

           Country  
7    United States  
9   United Kingdom  
10  United Kingdom  
11           Spain  
12     Netherlands  
13   United States  
16   United States  
18   United States  
23         Germany  
25          Canada

In [39]:
#While Checking df.info() 'YearsCodePro'- is given as Dtype (object=means string )
print(df['YearsCodePro'].unique())

['13' '4' '2' '7' '20' '1' '3' '10' '12' '29' '6' '28' '8' '23' '15' '25'
 '9' '11' 'Less than 1 year' '5' '21' '16' '18' '14' '32' '19' '22' '38'
 '30' '26' '27' '17' '24' '34' '35' '33' '36' '40' '39'
 'More than 50 years' '31' '37' '41' '45' '42' '44' '43' '50' '49']


In [40]:
#Taking action on YearsCodePro which is containing string value
def cleaned_experience(x):
    if x=="More than 50 years":
        return 50
    elif x=="Less than 1 year":
        return 0.5
    return float(x)




In [41]:
df['YearsCodePro'] = df['YearsCodePro'].apply(cleaned_experience)

In [42]:
df["YearsCodePro"].unique()

array([13. ,  4. ,  2. ,  7. , 20. ,  1. ,  3. , 10. , 12. , 29. ,  6. ,
       28. ,  8. , 23. , 15. , 25. ,  9. , 11. ,  0.5,  5. , 21. , 16. ,
       18. , 14. , 32. , 19. , 22. , 38. , 30. , 26. , 27. , 17. , 24. ,
       34. , 35. , 33. , 36. , 40. , 39. , 50. , 31. , 37. , 41. , 45. ,
       42. , 44. , 43. , 49. ])

In [43]:
#Taking action on Edlevel-Education Level Column 
print(df["EdLevel"].unique())

['Bachelor’s degree (B.A., B.S., B.Eng., etc.)'
 'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)'
 'Some college/university study without earning a degree'
 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)'
 'Associate degree (A.A., A.S., etc.)'
 'Professional degree (JD, MD, etc.)'
 'Other doctoral degree (Ph.D., Ed.D., etc.)'
 'I never completed any formal education' 'Primary/elementary school']


In [44]:
df['EdLevel'].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          9144
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       4821
Some college/university study without earning a degree                                2037
Other doctoral degree (Ph.D., Ed.D., etc.)                                             734
Associate degree (A.A., A.S., etc.)                                                    719
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     694
Professional degree (JD, MD, etc.)                                                     235
I never completed any formal education                                                  57
Primary/elementary school                                                               50
Name: EdLevel, dtype: int64

In [45]:
#Divided the Education Column EdLevel into 'Bachelor’s degree', 'Master’s degree', 'Less than a Bachelors','Post grad '
def cleaned_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'

df['EdLevel'] = df['EdLevel'].apply(cleaned_education)

In [46]:
#EACH UNIQUE EDUCATION LEVEL
df["EdLevel"].unique()

array(['Bachelor’s degree', 'Master’s degree', 'Less than a Bachelors',
       'Post grad'], dtype=object)

In [47]:
#APPLYING LABELENCODER TO EDUCATION-EdLevel,Country, COLUMN,
from sklearn.preprocessing import LabelEncoder
LE_education = LabelEncoder()
df['EdLevel'] = LE_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()

array([0, 2, 1, 3])

In [48]:
#CATEGORICAL VALUE CONVERTED INTO NUMERICAL
LE_country = LabelEncoder()
df['Country'] = LE_country.fit_transform(df['Country'])
df["Country"].unique()

array([13, 12, 10,  7,  4,  2,  6,  1,  3,  5, 11,  8,  0,  9])

In [49]:
df.head()

EdLevel  YearsCodePro    Salary  Country
7         0          13.0  116000.0       13
9         2           4.0   32315.0       12
10        0           2.0   40070.0       12
11        1           7.0   14268.0       10
12        1          20.0   38916.0        7

In [50]:
#Splitting data into features and labels
X = df.drop("Salary", axis=1)
y = df["Salary"]



In [51]:
#MACHINE LEARNING MODEL- LINEAR REGRESSION
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [52]:
#PREDICTED
y_pred = linear_reg.predict(X)

In [53]:
#CHECKED ITS ERROR
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))
error

39274.75368318509

In [54]:
#MACHINE LEARNING MODEL- DECISION TREE REGRESSOR
from sklearn.tree import DecisionTreeRegressor
dt_reg = DecisionTreeRegressor(random_state=0)
dt_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [55]:
#PREDICTED
y_pred = dt_reg.predict(X)

In [56]:
y_pred

array([128630.58139535,  68708.33333333,  44644.07608696, ...,
        96073.68292683, 146884.61538462, 110431.23376623])

In [57]:
error = np.sqrt(mean_squared_error(y, y_pred))
#SALARY PREDICTED
print("${:,.02f}".format(error))

$29,414.94


In [58]:
#MACHINE LEARNING MODEL- RANDOM FOREST REGRESSOR
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=0)
rf_reg.fit(X, y.values)

RandomForestRegressor(random_state=0)

In [59]:
#PREDICTED
y_pred = rf_reg.predict(X)

In [60]:
error = np.sqrt(mean_squared_error(y, y_pred))
#SALARY PREDICTED
print("${:,.02f}".format(error))

$29,487.31


In [61]:
#MACHINE LEARNING MODEL- GRIDSEARCHS CV
from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [62]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)

error = np.sqrt(mean_squared_error(y, y_pred))
#PREDICTED SALARY
print("${:,.02f}".format(error))

$30,428.51


In [63]:
#FEATURES COLUMNS
X

EdLevel  YearsCodePro  Country
7            0          13.0       13
9            2           4.0       12
10           0           2.0       12
11           1           7.0       10
12           1          20.0        7
...        ...           ...      ...
64113        1          15.0       13
64116        0           6.0       13
64122        1           4.0       13
64127        3          12.0       13
64129        2           4.0       13

[18491 rows x 3 columns]

In [64]:
#EVALUATING THE MODEL-ENTERING NEW DATA ON  X 
#EdLevel,YearCodePro,Country
X = np.array([["Master’s degree",15,"United States" ]])
X

array([['Master’s degree', '15', 'United States']], dtype='<U21')

In [65]:
#TRANFORMING INTO LABELENCODED FORM TO PARTICULAR COLUMNS
X[:, 0] = LE_education.transform(X[:,0])
X[:, 2] = LE_country.transform(X[:,2])
X = X.astype(float)
X

array([[ 2., 15., 13.]])

In [66]:
#PREDICTED SALARY
y_pred = regressor.predict(X)
y_pred

array([139427.26315789])

# SAVED AND LOADED INTO A PICKLE FILE

In [67]:
#IMPORTING THE LIBRARY -pickle SAVED AS "saved_steps.pkl" DUMPED 
import pickle
data = {"model": regressor, "le_country": LE_country, "le_education": LE_education}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [68]:
#LOADED THE PICKLE FILE
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

In [69]:
regressor_loaded = data["model"]
LE_country = data["le_country"]
LE_education = data["le_education"]

In [70]:
#SALARY PREDICTED
y_pred = regressor_loaded.predict(X)
y_pred

array([139427.26315789])